language: objective-c
osx_image: xcode8.2
rvm:
- 2.2

notifications:
  email: false
  
 cache:
  directories:
    - ./Unity

before_install:
- chmod a+x ./travis-scripts/*.sh

install:
- ./travis-scripts/install-unity.sh
- ./travis-scripts/install-libs.sh

script:
- ./travis-scripts/build-unity-project.sh

after_success:
- ./travis-scripts/export-package.sh